sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gnakatani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gnakatani/react-test npm test

after_success:
  - docker build -t gnakatani/multi-client ./client
  - docker build -t gnakatani/multi-nginx ./nginx
  - docker build -t gnakatani/multi-server ./server
  - docker build -t gnakatani/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gnakatani/multi-client
  - docker push gnakatani/multi-nginx
  - docker push gnakatani/multi-server
  - docker push gnakatani/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidockerenv-env'
  bucket_name: 'elasticbeanstalk-us-west-1-669505063135'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
